CREATE SCHEMA IF NOT EXISTS shopping_list;

USE shopping_list;

CREATE TABLE IF NOT EXISTS list_item (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS user
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS units
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
)