version: '3.1'

services:
  db:
    image: library/mysql:8.0.23
    restart: always
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=geheim"
    command: --default-authentication-plugin=mysql_native_password
