version: '3.1'

services:

  db:
    image: library/mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8_ao-infgs3#a3w^m
    ports:
      - 3306:3306